SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
-- 1. Alter Code Columns to VARCHAR
ALTER TABLE kds_cups MODIFY cup_code VARCHAR(10) NOT NULL COMMENT '杯型自定义编号';
ALTER TABLE kds_ice_options MODIFY ice_code VARCHAR(10) NOT NULL COMMENT '冰量自定义编号';
ALTER TABLE kds_sweetness_options MODIFY sweetness_code VARCHAR(10) NOT NULL COMMENT '甜度自定义编号';

-- Update kds_cups
UPDATE kds_cups SET cup_code = 'B01', cup_name = '700cc' WHERE id = 1;
UPDATE kds_cups SET cup_code = 'B02', cup_name = '500cc' WHERE id = 2;

-- Update kds_ice_options
UPDATE kds_ice_options SET ice_code = 'W01' WHERE id = 1;
UPDATE kds_ice_option_translations SET ice_option_name = '正常冰' WHERE ice_option_id = 1 AND language_code = 'zh-CN';
UPDATE kds_ice_option_translations SET ice_option_name = 'Hielo Normal' WHERE ice_option_id = 1 AND language_code = 'es-ES';
UPDATE kds_ice_options SET ice_code = 'W02' WHERE id = 2;
UPDATE kds_ice_option_translations SET ice_option_name = '少冰' WHERE ice_option_id = 2 AND language_code = 'zh-CN';
UPDATE kds_ice_option_translations SET ice_option_name = 'Menos Hielo' WHERE ice_option_id = 2 AND language_code = 'es-ES';
UPDATE kds_ice_options SET ice_code = 'W03' WHERE id = 3;
UPDATE kds_ice_option_translations SET ice_option_name = '去冰' WHERE ice_option_id = 3 AND language_code = 'zh-CN';
UPDATE kds_ice_option_translations SET ice_option_name = 'Sin Hielo' WHERE ice_option_id = 3 AND language_code = 'es-ES';
UPDATE kds_ice_options SET ice_code = 'W04' WHERE id = 4;
UPDATE kds_ice_option_translations SET ice_option_name = '温热' WHERE ice_option_id = 4 AND language_code = 'zh-CN';
UPDATE kds_ice_option_translations SET ice_option_name = 'Caliente' WHERE ice_option_id = 4 AND language_code = 'es-ES';
INSERT INTO kds_ice_options (ice_code) VALUES ('W05');
SET @last_id = LAST_INSERT_ID();
INSERT INTO kds_ice_option_translations (ice_option_id, language_code, ice_option_name) VALUES (@last_id, 'zh-CN', '冰沙');
INSERT INTO kds_ice_option_translations (ice_option_id, language_code, ice_option_name) VALUES (@last_id, 'es-ES', 'Granizado');

-- Update kds_sweetness_options
UPDATE kds_sweetness_options SET sweetness_code = 'T01' WHERE id = 1;
UPDATE kds_sweetness_option_translations SET sweetness_option_name = '推荐' WHERE sweetness_option_id = 1 AND language_code = 'zh-CN';
UPDATE kds_sweetness_option_translations SET sweetness_option_name = 'Recomendado' WHERE sweetness_option_id = 1 AND language_code = 'es-ES';
UPDATE kds_sweetness_options SET sweetness_code = 'T02' WHERE id = 2;
UPDATE kds_sweetness_option_translations SET sweetness_option_name = '少糖' WHERE sweetness_option_id = 2 AND language_code = 'zh-CN';
UPDATE kds_sweetness_option_translations SET sweetness_option_name = 'Menos Azúcar' WHERE sweetness_option_id = 2 AND language_code = 'es-ES';
UPDATE kds_sweetness_options SET sweetness_code = 'T03' WHERE id = 3;
UPDATE kds_sweetness_option_translations SET sweetness_option_name = '少少糖' WHERE sweetness_option_id = 3 AND language_code = 'zh-CN';
UPDATE kds_sweetness_option_translations SET sweetness_option_name = 'Poco Azúcar' WHERE sweetness_option_id = 3 AND language_code = 'es-ES';
UPDATE kds_sweetness_options SET sweetness_code = 'T04' WHERE id = 5;
UPDATE kds_sweetness_option_translations SET sweetness_option_name = '不另外加糖' WHERE sweetness_option_id = 5 AND language_code = 'zh-CN';
UPDATE kds_sweetness_option_translations SET sweetness_option_name = 'Sin Azúcar Añadido' WHERE sweetness_option_id = 5 AND language_code = 'es-ES';
UPDATE kds_sweetness_options SET deleted_at = NOW() WHERE id IN (4);

-- Update Products
UPDATE kds_products SET product_code = 'CP001', is_active = 1, deleted_at = NULL WHERE id = 1;
DELETE FROM kds_product_ice_options WHERE product_id = 1;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 1, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 1, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 1, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 1, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 1;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 1, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 1, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 1, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 1, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP002', is_active = 1, deleted_at = NULL WHERE id = 2;
DELETE FROM kds_product_ice_options WHERE product_id = 2;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 2, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 2, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 2, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 2, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 2;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 2, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 2, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 2, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 2, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP003', is_active = 1, deleted_at = NULL WHERE id = 3;
DELETE FROM kds_product_ice_options WHERE product_id = 3;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 3, id FROM kds_ice_options WHERE ice_code = 'W01';
DELETE FROM kds_product_sweetness_options WHERE product_id = 3;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 3, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 3, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 3, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 3, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP004', is_active = 1, deleted_at = NULL WHERE id = 4;
DELETE FROM kds_product_ice_options WHERE product_id = 4;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 4, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 4, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 4, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 4, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 4;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 4, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP005', is_active = 1, deleted_at = NULL WHERE id = 5;
DELETE FROM kds_product_ice_options WHERE product_id = 5;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 5, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 5, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 5, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 5, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 5;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 5, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 5, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 5, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 5, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP006', is_active = 1, deleted_at = NULL WHERE id = 6;
DELETE FROM kds_product_ice_options WHERE product_id = 6;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 6, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 6, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 6, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 6, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 6;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 6, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 6, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 6, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 6, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP007', is_active = 1, deleted_at = NULL WHERE id = 7;
DELETE FROM kds_product_ice_options WHERE product_id = 7;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 7, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 7, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 7, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 7, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 7;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 7, id FROM kds_sweetness_options WHERE sweetness_code = 'T04';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 7, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 7, id FROM kds_sweetness_options WHERE sweetness_code = 'T02';
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 7, id FROM kds_sweetness_options WHERE sweetness_code = 'T03';
UPDATE kds_products SET product_code = 'CP008', is_active = 1, deleted_at = NULL WHERE id = 8;
DELETE FROM kds_product_ice_options WHERE product_id = 8;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 8, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 8;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 8, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP009', is_active = 1, deleted_at = NULL WHERE id = 9;
DELETE FROM kds_product_ice_options WHERE product_id = 9;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 9, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 9;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 9, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP010', is_active = 1, deleted_at = NULL WHERE id = 10;
DELETE FROM kds_product_ice_options WHERE product_id = 10;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 10, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 10;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 10, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP011', is_active = 1, deleted_at = NULL WHERE id = 11;
DELETE FROM kds_product_ice_options WHERE product_id = 11;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 11, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 11;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 11, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP012', is_active = 1, deleted_at = NULL WHERE id = 12;
DELETE FROM kds_product_ice_options WHERE product_id = 12;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 12, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 12;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 12, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP013', is_active = 1, deleted_at = NULL WHERE id = 13;
DELETE FROM kds_product_ice_options WHERE product_id = 13;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 13, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 13, id FROM kds_ice_options WHERE ice_code = 'W01';
DELETE FROM kds_product_sweetness_options WHERE product_id = 13;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 13, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP014', is_active = 1, deleted_at = NULL WHERE id = 14;
DELETE FROM kds_product_ice_options WHERE product_id = 14;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 14, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 14, id FROM kds_ice_options WHERE ice_code = 'W01';
DELETE FROM kds_product_sweetness_options WHERE product_id = 14;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 14, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP022', is_active = 1, deleted_at = NULL WHERE id = 22;
DELETE FROM kds_product_ice_options WHERE product_id = 22;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 22, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 22;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 22, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP023', is_active = 1, deleted_at = NULL WHERE id = 23;
DELETE FROM kds_product_ice_options WHERE product_id = 23;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 23, id FROM kds_ice_options WHERE ice_code = 'W05';
DELETE FROM kds_product_sweetness_options WHERE product_id = 23;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 23, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP024', is_active = 1, deleted_at = NULL WHERE id = 24;
DELETE FROM kds_product_ice_options WHERE product_id = 24;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 24, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 24, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 24, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 24, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 24;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 24, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP025', is_active = 1, deleted_at = NULL WHERE id = 25;
DELETE FROM kds_product_ice_options WHERE product_id = 25;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 25, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 25, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 25, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 25, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 25;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 25, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP026', is_active = 1, deleted_at = NULL WHERE id = 26;
DELETE FROM kds_product_ice_options WHERE product_id = 26;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 26, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 26, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 26, id FROM kds_ice_options WHERE ice_code = 'W03';
DELETE FROM kds_product_sweetness_options WHERE product_id = 26;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 26, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP027', is_active = 1, deleted_at = NULL WHERE id = 27;
DELETE FROM kds_product_ice_options WHERE product_id = 27;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 27, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 27, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 27, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 27, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 27;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 27, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP028', is_active = 1, deleted_at = NULL WHERE id = 28;
DELETE FROM kds_product_ice_options WHERE product_id = 28;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 28, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 28, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 28, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 28, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 28;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 28, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP029', is_active = 1, deleted_at = NULL WHERE id = 29;
DELETE FROM kds_product_ice_options WHERE product_id = 29;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 29, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 29, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 29, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 29, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 29;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 29, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP030', is_active = 1, deleted_at = NULL WHERE id = 30;
DELETE FROM kds_product_ice_options WHERE product_id = 30;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 30, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 30, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 30, id FROM kds_ice_options WHERE ice_code = 'W03';
DELETE FROM kds_product_sweetness_options WHERE product_id = 30;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 30, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP031', is_active = 1, deleted_at = NULL WHERE id = 31;
DELETE FROM kds_product_ice_options WHERE product_id = 31;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 31, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 31, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 31, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 31, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 31;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 31, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP032', is_active = 1, deleted_at = NULL WHERE id = 32;
DELETE FROM kds_product_ice_options WHERE product_id = 32;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 32, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 32, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 32, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 32, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 32;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 32, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP033', is_active = 1, deleted_at = NULL WHERE id = 33;
DELETE FROM kds_product_ice_options WHERE product_id = 33;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 33, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 33, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 33, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 33, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 33;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 33, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET product_code = 'CP034', is_active = 1, deleted_at = NULL WHERE id = 34;
DELETE FROM kds_product_ice_options WHERE product_id = 34;
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 34, id FROM kds_ice_options WHERE ice_code = 'W02';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 34, id FROM kds_ice_options WHERE ice_code = 'W01';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 34, id FROM kds_ice_options WHERE ice_code = 'W03';
INSERT INTO kds_product_ice_options (product_id, ice_option_id) SELECT 34, id FROM kds_ice_options WHERE ice_code = 'W04';
DELETE FROM kds_product_sweetness_options WHERE product_id = 34;
INSERT INTO kds_product_sweetness_options (product_id, sweetness_option_id) SELECT 34, id FROM kds_sweetness_options WHERE sweetness_code = 'T01';
UPDATE kds_products SET is_active = 0, deleted_at = NOW() WHERE id IN (35,15,16,17,18,19,20,21);
SET FOREIGN_KEY_CHECKS=1;